---
- name: Install Daemon
  xbps:
    pkg: "{{ cron_implementation }}"
    state: present

- name: Configure alternative group
  command: xbps-alternatives -s "{{ cron_implementation }}" -g crond
  changed_when: false

- name: Enable Daemon
  runit:
    name: crond
    enabled: true
